spring.application.name=telemetria
server.port=${PORT:8080}

spring.datasource.url=${NEON_DB_URL}
spring.datasource.username=${NEON_DB_USER}
spring.datasource.password=${NEON_DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:localhost}